kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dpl
spec:
  selector:
    matchLabels:
      deploy: dpl
  template:
    metadata:
      labels:
        deploy: dpl
    spec:
      containers:
        - name: app
          image: app
          resources:
            requests:
              cpu: "0.1"
              memory: "100Mi"
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
